# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import intent_slot_service_pb2 as intent__slot__service__pb2


class ISServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IntentSlotRecognize = channel.unary_unary(
                '/intent.slot.v1.ISService/IntentSlotRecognize',
                request_serializer=intent__slot__service__pb2.IntentSlotRecognizeRequest.SerializeToString,
                response_deserializer=intent__slot__service__pb2.IntentSlotRecognizeResponse.FromString,
                )


class ISServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def IntentSlotRecognize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ISServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IntentSlotRecognize': grpc.unary_unary_rpc_method_handler(
                    servicer.IntentSlotRecognize,
                    request_deserializer=intent__slot__service__pb2.IntentSlotRecognizeRequest.FromString,
                    response_serializer=intent__slot__service__pb2.IntentSlotRecognizeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'intent.slot.v1.ISService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ISService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def IntentSlotRecognize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/intent.slot.v1.ISService/IntentSlotRecognize',
            intent__slot__service__pb2.IntentSlotRecognizeRequest.SerializeToString,
            intent__slot__service__pb2.IntentSlotRecognizeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
