# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: intent_slot_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19intent_slot_service.proto\x12\x0eintent.slot.v1\"-\n\x1aIntentSlotRecognizeRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\".\n\x1bIntentSlotRecognizeResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2}\n\tISService\x12p\n\x13IntentSlotRecognize\x12*.intent.slot.v1.IntentSlotRecognizeRequest\x1a+.intent.slot.v1.IntentSlotRecognizeResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'intent_slot_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INTENTSLOTRECOGNIZEREQUEST._serialized_start=45
  _INTENTSLOTRECOGNIZEREQUEST._serialized_end=90
  _INTENTSLOTRECOGNIZERESPONSE._serialized_start=92
  _INTENTSLOTRECOGNIZERESPONSE._serialized_end=138
  _ISSERVICE._serialized_start=140
  _ISSERVICE._serialized_end=265
# @@protoc_insertion_point(module_scope)
