# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: post_slot_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17post_slot_service.proto\x12\x0cpost.slot.v1\"+\n\x18PostSlotRecognizeRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\",\n\x19PostSlotRecognizeResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2s\n\tPSService\x12\x66\n\x11PostSlotRecognize\x12&.post.slot.v1.PostSlotRecognizeRequest\x1a\'.post.slot.v1.PostSlotRecognizeResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'post_slot_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _POSTSLOTRECOGNIZEREQUEST._serialized_start=41
  _POSTSLOTRECOGNIZEREQUEST._serialized_end=84
  _POSTSLOTRECOGNIZERESPONSE._serialized_start=86
  _POSTSLOTRECOGNIZERESPONSE._serialized_end=130
  _PSSERVICE._serialized_start=132
  _PSSERVICE._serialized_end=247
# @@protoc_insertion_point(module_scope)
